// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.accounts */
export type AccountsAccountId = string & { __brand: 'AccountsAccountId' };

/** Represents the table public.accounts */
export default interface Accounts {
  account_id: AccountsAccountId;

  email_address: string;

  password_hash: string;
}

/** Represents the initializer for the table public.accounts */
export interface AccountsInitializer {
  account_id: AccountsAccountId;

  email_address: string;

  password_hash: string;
}

/** Represents the mutator for the table public.accounts */
export interface AccountsMutator {
  account_id?: AccountsAccountId;

  email_address?: string;

  password_hash?: string;
}
