// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsId } from './Accounts';
import type { SetlistsId } from './Setlists';

/** Identifier type for public.accounts_setlists */
export type AccountsSetlistsId = string & { __brand: 'AccountsSetlistsId' };

/** Represents the table public.accounts_setlists */
export default interface AccountsSetlists {
  id: AccountsSetlistsId;

  account_id: AccountsId;

  setlist_id: SetlistsId;
}

/** Represents the initializer for the table public.accounts_setlists */
export interface AccountsSetlistsInitializer {
  id: AccountsSetlistsId;

  account_id: AccountsId;

  setlist_id: SetlistsId;
}

/** Represents the mutator for the table public.accounts_setlists */
export interface AccountsSetlistsMutator {
  id?: AccountsSetlistsId;

  account_id?: AccountsId;

  setlist_id?: SetlistsId;
}
