// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';
import type { SetlistsSetlistId } from './Setlists';

/** Identifier type for public.accounts_setlists */
export type AccountsSetlistsId = string & { __brand: 'AccountsSetlistsId' };

/** Represents the table public.accounts_setlists */
export default interface AccountsSetlists {
  id: AccountsSetlistsId;

  account_id: AccountsAccountId;

  setlist_id: SetlistsSetlistId;
}

/** Represents the initializer for the table public.accounts_setlists */
export interface AccountsSetlistsInitializer {
  id: AccountsSetlistsId;

  account_id: AccountsAccountId;

  setlist_id: SetlistsSetlistId;
}

/** Represents the mutator for the table public.accounts_setlists */
export interface AccountsSetlistsMutator {
  id?: AccountsSetlistsId;

  account_id?: AccountsAccountId;

  setlist_id?: SetlistsSetlistId;
}
