// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AccountsAccountId } from './Accounts';

/** Identifier type for public.artists */
export type ArtistsArtistId = string & { __brand: 'ArtistsArtistId' };

/** Represents the table public.artists */
export default interface Artists {
  artist_id: ArtistsArtistId;

  artist_name: string;

  creator_id: AccountsAccountId;
}

/** Represents the initializer for the table public.artists */
export interface ArtistsInitializer {
  artist_id: ArtistsArtistId;

  artist_name: string;

  creator_id: AccountsAccountId;
}

/** Represents the mutator for the table public.artists */
export interface ArtistsMutator {
  artist_id?: ArtistsArtistId;

  artist_name?: string;

  creator_id?: AccountsAccountId;
}
