// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.sessions */
export type SessionsId = string & { __brand: 'SessionsId' };

/** Represents the table public.sessions */
export default interface Sessions {
  id: SessionsId;

  account_id: string;
}

/** Represents the initializer for the table public.sessions */
export interface SessionsInitializer {
  id: SessionsId;

  account_id: string;
}

/** Represents the mutator for the table public.sessions */
export interface SessionsMutator {
  id?: SessionsId;

  account_id?: string;
}
