// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SetlistsSetlistId } from './Setlists';
import type { SongsSongId } from './Songs';

/** Identifier type for public.setlist_items */
export type SetlistItemsSetlistItemId = string & { __brand: 'SetlistItemsSetlistItemId' };

/** Represents the table public.setlist_items */
export default interface SetlistItems {
  setlist_item_id: SetlistItemsSetlistItemId;

  setlist_id: SetlistsSetlistId;

  song_id: SongsSongId;

  updated_at: Date;

  ordering: number;
}

/** Represents the initializer for the table public.setlist_items */
export interface SetlistItemsInitializer {
  setlist_item_id: SetlistItemsSetlistItemId;

  setlist_id: SetlistsSetlistId;

  song_id: SongsSongId;

  updated_at: Date;

  ordering: number;
}

/** Represents the mutator for the table public.setlist_items */
export interface SetlistItemsMutator {
  setlist_item_id?: SetlistItemsSetlistItemId;

  setlist_id?: SetlistsSetlistId;

  song_id?: SongsSongId;

  updated_at?: Date;

  ordering?: number;
}
