// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.setlists */
export type SetlistsSetlistId = string & { __brand: 'SetlistsSetlistId' };

/** Represents the table public.setlists */
export default interface Setlists {
  setlist_id: SetlistsSetlistId;

  setlist_name: string;

  creator_id: string;
}

/** Represents the initializer for the table public.setlists */
export interface SetlistsInitializer {
  setlist_id: SetlistsSetlistId;

  setlist_name: string;

  creator_id: string;
}

/** Represents the mutator for the table public.setlists */
export interface SetlistsMutator {
  setlist_id?: SetlistsSetlistId;

  setlist_name?: string;

  creator_id?: string;
}
