// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SongsId } from './Songs';
import type { SetlistsId } from './Setlists';

/** Identifier type for public.setlists_songs */
export type SetlistsSongsId = string & { __brand: 'SetlistsSongsId' };

/** Represents the table public.setlists_songs */
export default interface SetlistsSongs {
  id: SetlistsSongsId;

  song_id: SongsId;

  setlist_id: SetlistsId;
}

/** Represents the initializer for the table public.setlists_songs */
export interface SetlistsSongsInitializer {
  id: SetlistsSongsId;

  song_id: SongsId;

  setlist_id: SetlistsId;
}

/** Represents the mutator for the table public.setlists_songs */
export interface SetlistsSongsMutator {
  id?: SetlistsSongsId;

  song_id?: SongsId;

  setlist_id?: SetlistsId;
}
