// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.songs */
export type SongsSongId = string & { __brand: 'SongsSongId' };

/** Represents the table public.songs */
export default interface Songs {
  song_id: SongsSongId;

  song_name: string;

  creator_id: string;
}

/** Represents the initializer for the table public.songs */
export interface SongsInitializer {
  song_id: SongsSongId;

  song_name: string;

  creator_id: string;
}

/** Represents the mutator for the table public.songs */
export interface SongsMutator {
  song_id?: SongsSongId;

  song_name?: string;

  creator_id?: string;
}
