// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.songs */
export type SongsId = string & { __brand: 'SongsId' };

/** Represents the table public.songs */
export default interface Songs {
  id: SongsId;

  name: string;

  creator_id: string;
}

/** Represents the initializer for the table public.songs */
export interface SongsInitializer {
  id: SongsId;

  name: string;

  creator_id: string;
}

/** Represents the mutator for the table public.songs */
export interface SongsMutator {
  id?: SongsId;

  name?: string;

  creator_id?: string;
}
